---
- name: Make Installation of Kubectl
  hosts: k8s_master
  become: true
  tasks:
    - name: Get kubectl version
      command: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version
    
    - name: Install Kubectl binary
      command: |
        curl -LO "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
    
    - name: Validate it
      command: |
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      register: kubectl_sha256
    - debug: {var: kubectl_sha256.stdout}

    - name: Install kubectl binary to /usr/local/bin
      command: |
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: add permissions
      command: chmod +x kubectl

    - name: Create local bin directory if it does not exist
      command: mkdir -p ~/.local/bin
    
    - name: move kubectl to local bin
      command: |
        mv ./kubectl ~/.local/bin/kubectl

    - name: Validate Kubectl installation
      command: kubectl version --client
      register: kubectl_version
      become: false
    - debug: {var: kubectl_version.stdout}
      