---
- name: Setup Deployment Environment
  hosts: k8s_master
  become: true
  tasks:
    - name: Ensure Docker is installed
      command: docker --version
      register: docker_version
    - debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      
    - name: Login to Docker Hub
      command: docker login -u {{ username }} -p {{ password }}

    - name: Copy file directory to k8s_workstation server
      copy:
        src: "{{ controllers }}"
        dest: /home/ec2-user/

    - name: Create a replicaset on Kubernetes
      command: kubectl apply -f webapp-deploy.yml
      args:
        chdir: /home/ec2-user/controllers

    - name: Get the status of the replicaset
      command: kubectl get replicaset
      register: replicaset_status
    - debug:
        msg: "Replicaset status: {{ replicaset_status.stdout }}"

    - name: Create a LoadBalancer for the replicaset
      command: kubectl create -f load-balancer-service.yml
      args:
        chdir: /home/ec2-user/controllers

    - name: Get the status of the LoadBalancer
      command: kubectl get service
      register: service_status
    - debug: {var: service_status.stdout_lines}
      